DROP TABLE IF EXISTS uczniowie;
DROP TABLE IF EXISTS klasy;
DROP TABLE IF EXISTS przedmioty;
DROP TABLE IF EXISTS oceny;


CREATE TABLE uczniowie (
	id_uczen INTEGER PRIMARY KEY,
	imie TEXT,
	nazwisko TEXT,
	plec INTEGER,
	id_klasa INTEGER NOT NULL,
	egz_hum NUMERIC NOT NULL DEFAULT 0,
	egz_mat NUMERIC NOT NULL DEFAULT 0,
	egz_jez NUMERIC NOT NULL DEFAULT 0,
	FOREIGN KEY (id_klasa) REFERENCES klasy(id)
	ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE klasy (
	id_klasa INTEGER PRIMARY KEY AUTOINCREMENT,
	klasa TEXT(2),
	rok_naboru INTEGER,
	rok_matury INTEGER
);

CREATE TABLE przedmioty (
	id_przedmioty INTEGER PRIMARY KEY AUTOINCREMENT,
	przedmiot TEXT,
	imie_naucz TEXT,
	nazwisko_naucz TEXT,
	plec_naucz INTEGER
);

CREATE TABLE oceny (
	id_oceny INTEGER PRIMARY KEY AUTOINCREMENT,
	datad DATE,
	id_uczen INTEGER NOT NULL,
	id_przedmiot INTEGER NOT NULL,
	ocena INTEGER NOT NULL,
	FOREIGN KEY (id_uczen) REFERENCES uczniowie(id) ON DELETE CASCADE ON UPDATE NO ACTION
	FOREIGN KEY (id_przedmiot) REFERENCES przedmioty(id) ON DELETE CASCADE ON UPDATE NO ACTION
);